#controllers:
#  resource: ../src/Controller/
#  type: annotation
#
#kernel:
#  resource: ../src/Kernel.php
#  type: annotation

controllers:
    resource: ../src/Controller/
    type: attribute


accueil:
    path: /
    controller: App\Controller\PublicController::accueil